### PR TITLE
Replace loopback with Juggler for testing

### PR DESCRIPTION
**Pull request by superkhau**
Tests should be using Juggler from the start. This is also needed to separate
2.x and 3.x Juggler versions for testing/CI.

@bajtos PTAL
cc @qpresley 

Connect to strongloop/loopback#2724

### CODE REVIEW

**Comment by superkhau** [comment]
@bajtos @qpresley PTAL

**Comment by bajtos** [comment]
@superkhau the test are failing with an error that looks legitimate (not caused by missing MQ server):

```
1)  "before all" hook:
     TypeError: Cannot initialize connector {}: options object missing
      at Object.exports.createClient (node_modules/mqlight/mqlight.js:458:11)
      at MQLightConnector.connect (lib/mqlight-connector.js:98:11)
      at Object.initializeDataSource [as initialize] (lib/mqlight-connector.js:40:13)
      at DataSource.setup (node_modules/loopback-datasource-juggler/lib/datasource.js:339:19)
      at new DataSource (node_modules/loopback-datasource-juggler/lib/datasource.js:117:8)
      at Context.<anonymous> (test/mqlight.messaging.test.js:24:12)
```

PTAL

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
Fixed the failures, they are now the same as the errors in previous builds. Merging.

**Comment by superkhau** [comment]
Fixed the failures, they are now the same as the errors in previous builds. Merging.

**Pull request merged**
